queue_rules:
  - name: default
    queue_conditions:
      - "#approved-reviews-by>=1"
      - base=main
      - label=merge me daddy
    merge_conditions:
      - "#approved-reviews-by>=1"
    commit_message_template: |
      {{ title }} (#{{ number }})
      {{ body }}
    merge_method: squash

pull_request_rules:
  - name: backport patches to v0.0.2-alpha branch
    conditions:
      - base=main
      - label=backport/v0.0.2-alpha
    actions:
      backport:
        branches:
          - release/v0.0.2-alpha
  - name: automerge to main with label automerge and branch protection passing
    conditions: []
    actions:
      queue:
